import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Logo from '../public/Logo.png'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Smartran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      

      
      

      <div className='flex items-center justify-center opacity-20	'>
      <main>
            <Image 
            src={Logo}
            alt=''
            width="800px"
            height="600px">
            </Image>
            
          </main>
          </div>
          <Footer />
    </div>
  )
}
